export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_QUERY = "SET_QUERY";
export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const RESET_STATE = "RESET_STATE";
